table Query
	lineageTag: e9c6b608-7bb3-48bc-a34f-f7969a1cf3d6

	column CategoryCode
		dataType: string
		lineageTag: 7d0e78f2-5727-4e0b-8896-09d982ab9e95
		summarizeBy: none
		sourceColumn: CategoryCode

		annotation SummarizationSetBy = Automatic

	column CategoryName
		dataType: string
		lineageTag: 48b6f622-0020-474c-a7fa-c793efe74606
		summarizeBy: none
		sourceColumn: CategoryName

		annotation SummarizationSetBy = Automatic

	column CategoryGroup
		dataType: string
		lineageTag: 96a50ac6-8596-4b72-b43d-c77621c7d4ed
		summarizeBy: none
		sourceColumn: CategoryGroup

		annotation SummarizationSetBy = Automatic

	column DisplayOrder
		dataType: string
		lineageTag: 12c3d4a8-9a6a-411a-a2fb-9b983682142b
		summarizeBy: none
		sourceColumn: DisplayOrder

		annotation SummarizationSetBy = Automatic

	column IsAggregate
		dataType: string
		lineageTag: 71e47309-f09b-4c8a-b438-8ddf9a53222f
		summarizeBy: none
		sourceColumn: IsAggregate

		annotation SummarizationSetBy = Automatic

	partition Query = m
		mode: import
		source =
				let
				    Source   = Excel.Workbook(File.Contents(pRefMappingsPath), null, true),
				    Tbl      = Source{[Item = "tbl_CategoryMap", Kind = "Table"]}[Data],
				    Typed    = Table.TransformColumnTypes(
				                   Tbl,
				                   {
				                       {"CategoryCode",  type text},
				                       {"CategoryName",  type text},
				                       {"CategoryGroup", type text},
				                       {"DisplayOrder",  Int64.Type},
				                       {"IsAggregate",   type logical}
				                   }
				               ),
				
				    // Every code the API returned, mapped or not. The workbook supplies
				    // labels; it does not decide which codes exist.
				    ApiCodes = Table.Distinct(Table.SelectColumns(FactSectorSales, {"category_code"})),
				
				    Joined   = Table.NestedJoin(ApiCodes, {"category_code"}, Typed, {"CategoryCode"},
				                                "m", JoinKind.LeftOuter),
				    Expanded = Table.ExpandTableColumn(
				                   Joined, "m",
				                   {"CategoryName", "CategoryGroup", "DisplayOrder", "IsAggregate"}
				               ),
				
				    // Fallbacks for a code with no row in the workbook. A letter inside the
				    // code marks a Census "excluding" aggregate (44W72, 44Y72, 44Z72), which
				    // must stay out of share denominators even before anyone labels it.
				    Filled =
				        Table.ReplaceValue(
				            Expanded,
				            each [CategoryName],
				            each if [CategoryName] = null or [CategoryName] = ""
				                 then "(" & [category_code] & ") unmapped"
				                 else [CategoryName],
				            Replacer.ReplaceValue, {"CategoryName"}
				        ),
				
				    FilledGroup =
				        Table.ReplaceValue(
				            Filled,
				            each [CategoryGroup],
				            each if [CategoryGroup] = null or [CategoryGroup] = ""
				                 then "Unclassified"
				                 else [CategoryGroup],
				            Replacer.ReplaceValue, {"CategoryGroup"}
				        ),
				
				    FilledOrder =
				        Table.ReplaceValue(
				            FilledGroup,
				            each [DisplayOrder],
				            each if [DisplayOrder] = null then 9000 else [DisplayOrder],
				            Replacer.ReplaceValue, {"DisplayOrder"}
				        ),
				
				    FilledAgg =
				        Table.ReplaceValue(
				            FilledOrder,
				            each [IsAggregate],
				            each if [IsAggregate] <> null
				                 then [IsAggregate]
				                 else List.Count(List.Select(
				                          Text.ToList([category_code]),
				                          each not Value.Is(Value.FromText(_), type number))) > 0,
				            Replacer.ReplaceValue, {"IsAggregate"}
				        ),
				
				    Renamed = Table.RenameColumns(FilledAgg, {{"category_code", "CategoryCode"}}),
				
				    Final   = Table.SelectColumns(
				                  Renamed,
				                  {"CategoryCode", "CategoryName", "CategoryGroup", "DisplayOrder", "IsAggregate"}
				              )
				in
				    Final

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

